### PR TITLE
Bayesmethod xval

### PR DESCRIPTION
**Pull request by cranedroesch**
Flexible beta now works from command line.  Example usage:

`bayeschime  -p data/Downtown_parameters.csv -d data/Downtown_ts.csv -b flexible_beta -k 10`

`k` is the spline dimension, and `b` is the functional form for beta.  If you want flexible beta, indicate as above.  Default is logistic.  The penalty parameter for beta is in the params file.  Note you need to add a "pen_beta" and a "beta_intercept" parameter.  The former should be gaussian mean-zero, and the latter should be something like 10 -- some region that is logistic(x) is very close to 1.

Still plenty to be done; see the running list in issue #61

### CODE REVIEW

**Comment by cjbayesian** [comment]
Getting this error when I run the example usage:
```
Traceback (most recent call last):
  File "/Users/cchivers/anaconda2/envs/bayeschime/bin/bayeschime", line 11, in <module>
    load_entry_point('bayes-chime==0.1.0', 'console_scripts', 'bayeschime')()
  File "/Users/cchivers/proj/chime_sims/bayes_chime/normal/scripts/cli.py", line 302, in main
    {"hosp_min": 10, "vent_min": 1}, fit_kwargs
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/_extras.py", line 162, in empbayes_fit
    z = convert(_multiminex(z0buf, minfcn, **minargs).x)
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/_scipy.py", line 223, in __init__
    callback=analyzer, method='Nelder-Mead',
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/scipy/optimize/_minimize.py", line 588, in minimize
    return _minimize_neldermead(fun, x0, args, callback, **options)
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 585, in _minimize_neldermead
    fsim[k] = func(sim[k])
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 326, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/_extras.py", line 154, in minfcn
    fit = lsqfit.nonlinear_fit(**args)
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/__init__.py", line 681, in __init__
    p0, nf, self._chiv, tol=tol, maxit=maxit, **self.fitterargs
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/_scipy.py", line 160, in __init__
    **extra_args
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/scipy/optimize/_lsq/least_squares.py", line 835, in least_squares
    J0 = jac(x0, *args, **kwargs)
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/_scipy.py", line 150, in Dfun
    fx = f(_valder + x)
  File "_utilities.pyx", line 67, in lsqfit._utilities.chiv
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/lsqfit/__init__.py", line 1876, in flatfcn_ad
    ans = fcn(po) if x is False else fcn(x, po)
  File "/Users/cchivers/proj/chime_sims/bayes_chime/normal/models/base.py", line 181, in fit_fcn
    df = self.propagate_uncertainties(xx, pp)
  File "/Users/cchivers/proj/chime_sims/bayes_chime/normal/models/base.py", line 139, in propagate_uncertainties
    df = DataFrame(data=self._iterate_simulation(**pars)).set_index("date")
  File "/Users/cchivers/anaconda2/envs/bayeschime/lib/python3.7/site-packages/pandas/core/frame.py", line 445, in __init__
    data = list(data)
  File "/Users/cchivers/proj/chime_sims/bayes_chime/normal/models/base.py", line 161, in _iterate_simulation
    inp_pars = self.update_parameters(date, **pars)
  File "/Users/cchivers/proj/chime_sims/bayes_chime/normal/scripts/cli.py", line 153, in flexible_beta
    ppars["beta"] = kwargs["beta"] * (1-1/(1+np.exp(kwargs['beta_intercept'] + X@kwargs['TI_coef'])))
TypeError: ufunc 'matmul' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by DougManuel** [comment]
Update READ.me with your example usage for this PR.

**Comment by cjbayesian** [comment]
Got it working. I get this output. Is this the expected behaviour (seems like a narrow CI)? 
image

**Comment by ckoerber** [comment]
The width of CI bands depends on the size of the estimated data-errors (hosp and vent admissions), which are also quite narrow. 

I believe this script uses the empirical Bayes criterium to estimate data uncertainties. Simplifying how it works, this criterium tries to optimize the probability that the model describes the data. If there are more model parameters, it might be easier to describe the data and thus this criterium suggests that the data errors are smaller. Thus this estimation process might be a potential source for overfitting.

If possible, it might be a good cross check to run the same analysis against data uncertainty estimations motivated through other means (these can be specified by file through the `-y` flag).

**Comment by cjbayesian** [comment]
Great. I was able to run it with the `-y` flag and get reasonable results.

**Pull request merged**
